[project]
name = "triton-eval"
version = "0.1.0"
description = "A simple triton/cuda execution framework"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "torch==2.6+cu126; sys_platform != 'darwin'",
    "torch; sys_platform == 'darwin'",
    "numpy",
    "pydantic",
    "setuptools",
    "ninja",
    "rich",
    "simple_parsing",
    "modal>=0.73.153",
    "datasets>=3.5.0",
    "openai>=1.72.0",
    "weave>=0.51.42",
    "smolagents>=1.13.0",
    "ipykernel>=6.29.5",
]

[tool.uv.sources]
torch = [
  { index = "pytorch-cu126", marker = "sys_platform != 'darwin'"},
]

[[tool.uv.index]]
name = "pytorch-cu126"
url = "https://download.pytorch.org/whl/cu126"
explicit = true

[tool.setuptools]
packages = ["triton_eval"]

[dependency-groups]
dev = [
    "pytest>=8.3.5",
]
lint = [
    "ruff>=0.11.4",
]
