[project]
name = "triton-eval"
version = "0.1.0"
description = "A simple triton/cuda execution framework"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "torch==2.6",
    "numpy",
    "pydantic",
    "setuptools",
    "ninja",
    "rich",
    "simple_parsing",
    "modal>=0.73.153",
    "datasets>=3.5.0",
    "openai>=1.72.0",
    "weave>=0.51.42",
    "smolagents>=1.13.0",
    "ipykernel>=6.29.5",
    "vllm>=0.8.4",
    "trl",
]

[tool.setuptools]
packages = ["triton_eval"]

[tool.uv.sources]
trl = { git = "https://github.com/huggingface/trl.git", rev = "0dad4eb7ca8de6f93a76752a5773c0baecd4a3d3" }

[dependency-groups]
dev = [
    "pytest>=8.3.5",
]
lint = [
    "ruff>=0.11.4",
]
