apiVersion: v1
kind: Pod
metadata:
  name: debug-gpu-node
  labels:
    purpose: node-debug
spec:
  # target your node
  nodeName: <your-node-name>
  # never restart once you exit
  restartPolicy: Never
  # see host PIDs
  hostPID: true

  containers:
  - name: gpu-debug
    image: nvidia/cuda:12.0-base
    # keep stdin/tty for exec
    stdin: true
    tty: true
    # idle forever so you can kubectl exec into it
    command: ["bash", "-c", "trap 'exit 0' SIGTERM SIGINT; while true; do sleep 30; done"]
    securityContext:
      privileged: true
    resources:
      limits:
        nvidia.com/gpu: "8"
        cpu: "32"
        memory: "1600Gi"
      requests:
        nvidia.com/gpu: "8"
        cpu: "32"
        memory: "1600Gi"
    volumeMounts:
      # mount host fs for logs, driver dirs, etc.
      - name: host-root
        mountPath: /host

  volumes:
    - name: host-root
      hostPath:
        path: /
        type: Directory 