base_model: Qwen/Qwen2.5-7B-Instruct
# Automatically upload checkpoint and final model to HF
# hub_model_id: username/custom_model_name

load_in_8bit: false
load_in_4bit: false
strict: false

torch_compile: true

rl: grpo
trl:
  beta: 0.0
  max_completion_length: 2048
  use_vllm: true
  reward_funcs:
    # - gsm8k_grpo.correctness_reward_func
    # - gsm8k_grpo.int_reward_func
    # - gsm8k_grpo.strict_format_reward_func
    # - gsm8k_grpo.soft_format_reward_func
    # - gsm8k_grpo.xmlcount_reward_func
    - rewards.think_reward
    - rewards.one_code_blob_reward
    - rewards.reward_code_runs
  vllm_gpu_memory_utilization: 0.9
  vllm_max_model_len: 2048
  num_generations: 14

chat_template: qwen_25
datasets:
  - path: ./train_dataset
dataset_prepared_path: /workspace/data/last_run_prepared
skip_prepare_dataset: true
val_set_size: 0.0
output_dir: /workspace/data/axolotl-artifacts/r1-outputs

dataloader_prefetch_factor: 32
dataloader_num_workers: 2
dataloader_pin_memory: true

gc_steps: 1

sequence_len: 2048
sample_packing: false
eval_sample_packing: false
pad_to_sequence_len: false

wandb_project: axolotl-grpo
wandb_entity: grpo-cuda
wandb_name:

gradient_accumulation_steps: 8
micro_batch_size: 2  # should match num_generations / num_gpus
num_epochs: 1

optimizer: adamw_torch_fused
lr_scheduler: constant_with_warmup
learning_rate: 1.0e-6
max_grad_norm: 1.0
weight_decay: 0.1

bf16: true
tf32: true

gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
flash_attention: true

logging_steps: 1
warmup_steps: 100
evals_per_epoch: 1
saves_per_epoch: 4