# base_model: Qwen/Qwen2.5-Coder-14B-Instruct
base_model: winglian/seed-coder-triton-8b-v1

# base_model: /workspace/data/axolotl-artifacts/grpo-beta-zero
# Automatically upload checkpoint and final model to HF
# hub_model_id: username/custom_model_name

load_in_8bit: false
load_in_4bit: false
strict: false

# torch_compile: true

rl: grpo
trl:
  beta: 0.0
  max_completion_length: 8192
  num_generations: 16
  use_vllm: true
  vllm_server_host: "axolotl-vllm-service"
  vllm_server_port: 8000
  reward_funcs:
    - rewards.think_reward
    - rewards.one_code_blob_reward
    - rewards.reward_code_runs
    - rewards.imports_decorator_reward
    - rewards.constexpr_reward
    - rewards.valid_tl_methods_reward
    - rewards.masks_load_store_reward
    - rewards.torch_empty_penalty
    - rewards.torch_zeros_reward
  reward_weights:
  vllm: # stuff used by the trainer to call the vllm server
    vllm_gpu_memory_utilization: 0.9


chat_template: llama3
datasets:
  - path: tcapelle/train_ds_triton
    split: train
dataset_prepared_path: /workspace/data/last_run_prepared
skip_prepare_dataset: true
val_set_size: 0.0
output_dir: /model-checkpoints/seed-coder-8b

dataloader_prefetch_factor: 32
dataloader_num_workers: 2
dataloader_pin_memory: true

gc_steps: 1

sequence_len: 8192
sample_packing: false
eval_sample_packing: false
pad_to_sequence_len: false

wandb_project: axolotl-grpo
wandb_entity: grpo-cuda
wandb_name: seed-coder-8b
wandb_log_model: checkpoint

gradient_accumulation_steps: 2
micro_batch_size: 12  # should match num_generations / num_gpus
num_epochs: 3

optimizer: adamw_torch_fused
lr_scheduler: constant_with_warmup
learning_rate: 5.0e-7
max_grad_norm: 0.5
weight_decay: 0.01

bf16: true
tf32: true

gradient_checkpointing: True
gradient_checkpointing_kwargs:
  use_reentrant: false
flash_attention: true

logging_steps: 1
warmup_steps: 100
evals_per_epoch: 1
saves_per_epoch: 1
save_total_limit: 2
save_only_model: true

gc_steps: 1