base_model: Qwen/Qwen2.5-14B-Instruct
# base_model: /workspace/data/axolotl-artifacts/grpo-beta-zero
# Automatically upload checkpoint and final model to HF
# hub_model_id: username/custom_model_name

load_in_8bit: false
load_in_4bit: false
strict: false

# torch_compile: true

rl: grpo
trl:
  beta: 0.0
  max_completion_length: 4096
  use_vllm: true
  reward_funcs:
    - rewards.think_reward
    - rewards.one_code_blob_reward
    - rewards.reward_code_runs
    - rewards.imports_decorator_reward
    - rewards.constexpr_reward
    - rewards.valid_tl_methods_reward
    - rewards.masks_load_store_reward
    - rewards.torch_empty_penalty
    - rewards.torch_zeros_reward
  reward_weights:
  vllm_gpu_memory_utilization: 0.9
  # vllm_max_model_len: 4096 # May be useful for big models/small GPUs
  num_generations: 12

chat_template: qwen_25
datasets:
  - path: tcapelle/train_ds_triton
    split: train
dataset_prepared_path: /workspace/data/last_run_prepared
skip_prepare_dataset: true
val_set_size: 0.0
output_dir: /root/models/grpo-beta-zero-14b-v3

dataloader_prefetch_factor: 32
dataloader_num_workers: 2
dataloader_pin_memory: true

gc_steps: 1

sequence_len: 4096
sample_packing: false
eval_sample_packing: false
pad_to_sequence_len: false

wandb_project: axolotl-grpo
wandb_entity: grpo-cuda
wandb_name: grpo-qwen14b-v3

gradient_accumulation_steps: 3
micro_batch_size: 8  # should match num_generations / num_gpus
num_epochs: 20

optimizer: adamw_torch_fused
lr_scheduler: constant_with_warmup
learning_rate: 1.0e-6
max_grad_norm: 1.0
weight_decay: 0.01

bf16: true
tf32: true

gradient_checkpointing: True
gradient_checkpointing_kwargs:
  use_reentrant: false
flash_attention: true

logging_steps: 1
warmup_steps: 100
evals_per_epoch: 1
saves_per_epoch: 1
save_total_limit: 4