apiVersion: v1
kind: Pod
metadata:
  name: gpu-debug
spec:
  # nodeName: gf2da52              # pin to your bad node
  restartPolicy: Never
  containers:
  - name: gpu-debug
    image: nvidia/cuda:12.6.3-cudnn-runtime-ubuntu22.04
    command: ["/bin/bash", "-c", "sleep infinity"]
    stdin: true
    tty: true
    securityContext:
      privileged: true
    resources:
      limits:
        nvidia.com/gpu: "8"
        cpu: "32"
        memory: "1600Gi"
      requests:
        cpu: "32"
        memory: "1600Gi"
        nvidia.com/gpu: "8"